### ISSUE TITLE
Decimal place issue in sidebar calculator

### ISSUE THREAD

**Issue by uli-on** [AndreAle94/moneywallet#108]
Example to try:
100-99.99 
is always an awry 
0.010000000000005116
on my device. On somebody else's too? 

Does not happen in the transaction calculator, btw. 

MoneyWallet 4.0.5.6 (from F-Droid) 
Android 6.0.1, Moto G4

**Comment by bendaf** [comment]
Yep, it's the same on my device too.

**Comment by bendaf** [comment]
It should be the problem with the [double representation](https://stackoverflow.com/questions/9911016/double-subtraction-precision-issue#). Based on that and [this](https://stackoverflow.com/a/322875/3162918) answers I would suggest to use BigDecimal instead of double in the calculator. I will create a PR.
