### ISSUE TITLE
How do i add Icons to the source

### ISSUE THREAD

**Issue by zekiz774** [AndreAle94/moneywallet#134]
Hi
I want to add my own icons to the source, but i don't know where to add them.

**Comment by femto-code** [comment]
Hi,
i also would like to have more icons.
In order to understand the problem with licencing in an open-source repository consider reading #12, #52, #129, #133 which lead in a similar question. I guess the icon pack has to be referenced anywhere in the code, I'll have a look on that.
Btw, I really like the app, it has so much potential and an active development with updates would be very nice. 👍

**Comment by femto-code** [comment]
It appears that all icons from the iconpack used by this app (the part that is free to use open-source) are located [here](https://github.com/AndreAle94/moneywallet/tree/master/app/src/main/res/drawable).
The format is called "**_Android vector drawable XML_**" and there are converters online for that.

As far as I have examined the app's code all icons are referenced in a JSON file which is located [here](https://github.com/AndreAle94/moneywallet/blob/master/app/src/main/assets/resources/icons.json).

So in fact **it is possible to add your own icons**, by:
1. placing a XML file in the first location
2. referencing its existence in the JSON file mentioned in the second location

It would be interesting for me, whether this works.

**Comment by AndreAle94** [comment]
Hi,
Exactly! If you want to add additional icons you should place them inside the drawable folder and insert a reference inside the json file.

If you need to add additional icon categories (or modify an esisting one) you should add/edit the string inside the string.xml for translations.

I'm very busy now and i have no time to devote to this project. Contributions are very welcome btw.
