### ISSUE TITLE
[Feature request] Import csv

### ISSUE THREAD

**Issue by Vercety87** [AndreAle94/moneywallet#22]
Hi, could you add an import csv feature ?

Your apps looks great but I use My Budget Book apps for many years, I can't start from scratch with a new apps. Thanks.

**Comment by AndreAle94** [comment]
Yes, it is a work in progress in import-export-data branch. It is almost finished.

**Comment by ariel-tij** [comment]
Hey, I'm dealing with the same issue reported by @ernesto-albarez. I'm trying to move from Money lover to MoneyWallet, but I'm unable to import the csv file. I modified the column titles in order to match the required ones on your app, and still no result. Then I tried with the example provided above and I get the same issue: missing required columns.
Any thoughts?
Thanks in advance!
