### ISSUE TITLE
[wiki] How to spend savings?

### ISSUE THREAD

**Issue by nr458h** [AndreAle94/moneywallet#33]
Hi I like the savings feature, and use it already a lot. But I don't get how to spend those saveings? With withdraw everything I need to create two transactions??
If this is the planned behavior I would suggest to add the ability to spend the savings directly.

**Comment by AndreAle94** [comment]
Yes, savings are considered as particular wallets. When a saving has been completed, all the money must be withdrawn and deposited on a real user wallet before being spent. It's the same thing that happens when you break the piggy bank to use the savings: the money goes into your wallet and they are ready to be spent. The change you request can not be made on the current database structure.
