### ISSUE TITLE
Minor Bug relating to font color in dark mode

### ISSUE THREAD

**Issue by akashpal-21** [AndreAle94/moneywallet#78]
In the user interface, if i choose dark or deep black, the font in "Income color" remains black and thus unreadable.. Minor issue though

**Comment by AndreAle94** [comment]
Sorry but i'm not able to replicate this bug. Which 'Income color' label do you mean exactly? in which screen?

**Comment by lbrfabio** [comment]
I think my problem is probably related. After the latest update of november the theme is having some problems both on dark and light theme.
Whatever color I choose inside the app is ignored except for the sidebar and status bar. It's always indigo. Also both dark and deep dark are basically all black (font and background) while in light mode some text like titles are also black.
My phone is the Pixel 3 with Android 10. The problem is present with the dark theme or light theme at system level. 

![Screenshot_20191118-211049](https://user-images.githubusercontent.com/2915605/69090473-349fce00-0a49-11ea-99d0-dc1508f88954.png)
![Screenshot_20191118-211128](https://user-images.githubusercontent.com/2915605/69090475-349fce00-0a49-11ea-8586-97222d34fa14.png)

**Comment by jojo599k** [comment]
I have got the same problem.
Buid number: 4.0.5. 4 from F-Droid
This bug appeared when I updated to Android 10 and use the Dark Mode of Android.
![Screenshot_20191207-084209__01](https://user-images.githubusercontent.com/28629015/70371047-31706300-18ce-11ea-942e-1874f394be87.jpg)
![Screenshot_20191207-084200](https://user-images.githubusercontent.com/28629015/70371048-3208f980-18ce-11ea-82f5-d291c541045a.jpg)
You Cann see there my Settings and the bug.

**Comment by AndreAle94** [comment]
Can you try v4.0.5.5 please?

**Comment by jojo599k** [comment]
Fixed it for me. What is about the others @akashpal-21 @lbrfabio?

**Comment by lbrfabio** [comment]
After v4.0.5.10 the bug has returned. I Had to revert to 4.0.5.8.
I'm on Android 12, not sure if it is related, but 4.0.5.8 is fine so probably not
